// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallenge1.Data.Context;

#nullable disable

namespace TechChallenge1.Data.Migrations
{
    [DbContext(typeof(techchallengeDbContext))]
    [Migration("20240512234237_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechChallenge1.Domain.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Contact", "TechChallenge1");
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("State", "TechChallenge1");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57342861-1127-4028-92c2-bded69fc4713"),
                            DDD = 11,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("ea53d08c-030d-4f20-a323-840832caa7de"),
                            DDD = 21,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("eeaf7be8-9a30-483d-b566-70bf4960a16a"),
                            DDD = 22,
                            Name = "Vitória"
                        },
                        new
                        {
                            Id = new Guid("c4b75fee-9622-4060-8158-ffde35d9f772"),
                            DDD = 31,
                            Name = "Belo Horizonte"
                        },
                        new
                        {
                            Id = new Guid("1a0ff11d-3c4c-4f1a-a5eb-5e7921b1a5be"),
                            DDD = 41,
                            Name = "Curitiba"
                        },
                        new
                        {
                            Id = new Guid("7bb3d506-48b5-406c-aa13-d44667075fa2"),
                            DDD = 48,
                            Name = "Florianópolis"
                        },
                        new
                        {
                            Id = new Guid("04b0a9cd-7fd3-4ecf-9aa0-3a2bb3cf3092"),
                            DDD = 51,
                            Name = "Porto Alegre"
                        },
                        new
                        {
                            Id = new Guid("bb3a17cc-c20b-4d0f-987a-4d38ddb4c1ee"),
                            DDD = 61,
                            Name = "Brasília"
                        },
                        new
                        {
                            Id = new Guid("cac38b0c-8472-40b4-927e-500ecf79f525"),
                            DDD = 62,
                            Name = "Goiânia"
                        },
                        new
                        {
                            Id = new Guid("31aafc9d-33dd-4d54-8446-662eb61792b4"),
                            DDD = 63,
                            Name = "Palmas"
                        },
                        new
                        {
                            Id = new Guid("ddf5a4a4-badc-4f9b-aabd-758fc9343125"),
                            DDD = 65,
                            Name = "Cuiabá"
                        },
                        new
                        {
                            Id = new Guid("614c1500-37cd-480d-9222-c73099385b48"),
                            DDD = 67,
                            Name = "Campo Grande"
                        },
                        new
                        {
                            Id = new Guid("96d606c6-81ec-4d1e-9c15-96b6a48c7782"),
                            DDD = 68,
                            Name = "Rio Branco"
                        },
                        new
                        {
                            Id = new Guid("641bec58-5f43-4050-b35d-db730977066a"),
                            DDD = 69,
                            Name = "Porto Velho"
                        },
                        new
                        {
                            Id = new Guid("98cc416d-e609-4b0f-a298-7b7b64e081bf"),
                            DDD = 71,
                            Name = "Salvador"
                        },
                        new
                        {
                            Id = new Guid("5fa9a197-430d-4039-9012-b1befcae2d04"),
                            DDD = 79,
                            Name = "Aracaju"
                        },
                        new
                        {
                            Id = new Guid("8a264b15-bf48-41e2-bb97-39e4ea6e5598"),
                            DDD = 81,
                            Name = "Recife"
                        },
                        new
                        {
                            Id = new Guid("24c2ea8d-f516-4c5a-9706-0a3a05114460"),
                            DDD = 82,
                            Name = "Maceió"
                        },
                        new
                        {
                            Id = new Guid("91f2391c-5a62-456c-a3ee-2f58224a21c7"),
                            DDD = 83,
                            Name = "João Pessoa"
                        },
                        new
                        {
                            Id = new Guid("65a93ed5-05d6-4b78-8590-110b51571962"),
                            DDD = 84,
                            Name = "Natal"
                        },
                        new
                        {
                            Id = new Guid("b75b2f74-aa85-4af3-acdd-b68f9e4c723e"),
                            DDD = 85,
                            Name = "Fortaleza"
                        },
                        new
                        {
                            Id = new Guid("a7df5980-e024-48a9-9ab4-332a1c7edd8e"),
                            DDD = 86,
                            Name = "Teresina"
                        },
                        new
                        {
                            Id = new Guid("fe0b54d6-2161-4109-9c9f-c96e4503595a"),
                            DDD = 91,
                            Name = "Belém"
                        },
                        new
                        {
                            Id = new Guid("ab97087e-8073-4a7b-ba7a-6ff826357c05"),
                            DDD = 92,
                            Name = "Manaus"
                        },
                        new
                        {
                            Id = new Guid("20a752cc-9fed-4495-bffd-57af59f41a2a"),
                            DDD = 95,
                            Name = "Boa Vista"
                        },
                        new
                        {
                            Id = new Guid("2adb7410-d10c-4d03-b355-ee5ac83b46c5"),
                            DDD = 96,
                            Name = "Macapá"
                        },
                        new
                        {
                            Id = new Guid("03bbeed2-79db-4d04-8d22-5f7399fbd04a"),
                            DDD = 98,
                            Name = "São Luís"
                        });
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.Contact", b =>
                {
                    b.HasOne("TechChallenge1.Domain.Models.State", "State")
                        .WithMany("Contacts")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.State", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
