// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallenge1.Data.Context;

#nullable disable

namespace TechChallenge1.Data.Migrations
{
    [DbContext(typeof(techchallengeDbContext))]
    [Migration("20240512151921_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechChallenge1.Domain.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Contact", "TechChallenge1");
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("State", "TechChallenge1");

                    b.HasData(
                        new
                        {
                            Id = new Guid("057e3f0a-8ee2-4bbf-afd7-aabdd9c89291"),
                            DDD = 11,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("8e0af3e5-548e-475b-9a68-f4ae98b3e5a8"),
                            DDD = 21,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("ab5fbc48-e0d5-44eb-9189-47fe15f9f576"),
                            DDD = 22,
                            Name = "Vitória"
                        },
                        new
                        {
                            Id = new Guid("a1bbee87-6805-4ee2-a07b-4027d7353765"),
                            DDD = 31,
                            Name = "Belo Horizonte"
                        },
                        new
                        {
                            Id = new Guid("16f0cfe1-989c-4643-a750-0639f00641f7"),
                            DDD = 41,
                            Name = "Curitiba"
                        },
                        new
                        {
                            Id = new Guid("35f8abcb-4c52-400b-9659-3ddcbc960744"),
                            DDD = 48,
                            Name = "Florianópolis"
                        },
                        new
                        {
                            Id = new Guid("cec1b553-fdcc-497e-aa9f-117f3598a55f"),
                            DDD = 51,
                            Name = "Porto Alegre"
                        },
                        new
                        {
                            Id = new Guid("151e4972-eebb-4d42-af90-e43b892b3398"),
                            DDD = 61,
                            Name = "Brasília"
                        },
                        new
                        {
                            Id = new Guid("a8302dea-becf-401f-8820-7ba4e4ed8638"),
                            DDD = 62,
                            Name = "Goiânia"
                        },
                        new
                        {
                            Id = new Guid("76c2b443-183e-47b7-9f5a-7b0abfb9c86b"),
                            DDD = 63,
                            Name = "Palmas"
                        },
                        new
                        {
                            Id = new Guid("1a7e0bac-647a-46c5-99ed-6da690cc6343"),
                            DDD = 65,
                            Name = "Cuiabá"
                        },
                        new
                        {
                            Id = new Guid("fb8f29b9-a17e-46e1-9299-4b765a16d647"),
                            DDD = 67,
                            Name = "Campo Grande"
                        },
                        new
                        {
                            Id = new Guid("391b8450-a646-403e-880b-cf19e5482768"),
                            DDD = 68,
                            Name = "Rio Branco"
                        },
                        new
                        {
                            Id = new Guid("6581ab83-fac6-4b69-91cb-daf4ee24da39"),
                            DDD = 69,
                            Name = "Porto Velho"
                        },
                        new
                        {
                            Id = new Guid("7231c076-d737-404f-a17d-880210f33d67"),
                            DDD = 71,
                            Name = "Salvador"
                        },
                        new
                        {
                            Id = new Guid("7e2e0415-fc56-4790-92b5-7106c584296e"),
                            DDD = 79,
                            Name = "Aracaju"
                        },
                        new
                        {
                            Id = new Guid("8281c06a-386f-41e6-a3eb-4a47116ecd55"),
                            DDD = 81,
                            Name = "Recife"
                        },
                        new
                        {
                            Id = new Guid("8ae53368-db49-417c-8810-25e4de5291e4"),
                            DDD = 82,
                            Name = "Maceió"
                        },
                        new
                        {
                            Id = new Guid("89f6cd24-86ee-4e8d-9822-5ea63cdd2db3"),
                            DDD = 83,
                            Name = "João Pessoa"
                        },
                        new
                        {
                            Id = new Guid("6b7056a2-9e02-412f-b8c7-52b48484596a"),
                            DDD = 84,
                            Name = "Natal"
                        },
                        new
                        {
                            Id = new Guid("da0d0447-10e7-4905-a020-b61eb947fbc7"),
                            DDD = 85,
                            Name = "Fortaleza"
                        },
                        new
                        {
                            Id = new Guid("d834c85d-b467-4eb4-b2e8-59f3517a18df"),
                            DDD = 86,
                            Name = "Teresina"
                        },
                        new
                        {
                            Id = new Guid("18cec7ef-481e-4b5b-bb82-b1a68576c7ec"),
                            DDD = 91,
                            Name = "Belém"
                        },
                        new
                        {
                            Id = new Guid("7584c8f3-5a1f-4a4d-bab0-f46422ad7c8d"),
                            DDD = 92,
                            Name = "Manaus"
                        },
                        new
                        {
                            Id = new Guid("0e713c33-8d65-424d-90c7-bef3eac6e180"),
                            DDD = 95,
                            Name = "Boa Vista"
                        },
                        new
                        {
                            Id = new Guid("78b89ae2-0568-4cb4-8ec4-8765e11d5a63"),
                            DDD = 96,
                            Name = "Macapá"
                        },
                        new
                        {
                            Id = new Guid("4510a7dd-b8a5-4f83-bf8c-511d98826f97"),
                            DDD = 98,
                            Name = "São Luís"
                        });
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.Contact", b =>
                {
                    b.HasOne("TechChallenge1.Domain.Models.State", "State")
                        .WithMany("Contacts")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.State", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
