// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallenge1.Data.Context;

#nullable disable

namespace TechChallenge1.Data.Migrations
{
    [DbContext(typeof(techchallengeDbContext))]
    partial class techchallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechChallenge1.Domain.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Contact", "TechChallenge1");
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("Id");

                    b.ToTable("State", "TechChallenge1");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07a0c26f-80c2-4caa-aa11-fbc23720f911"),
                            DDD = 11,
                            Name = "11 - São Paulo"
                        },
                        new
                        {
                            Id = new Guid("117d05e9-48b2-41d9-bb86-cf030954133e"),
                            DDD = 21,
                            Name = "21 - Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("df062898-4164-41bf-83f2-7522a4aff655"),
                            DDD = 22,
                            Name = "27 - Vitória"
                        },
                        new
                        {
                            Id = new Guid("c20f03ac-13d1-4ac5-b31a-710c11133bc8"),
                            DDD = 31,
                            Name = "31 - Belo Horizonte"
                        },
                        new
                        {
                            Id = new Guid("b2eb2523-b7c5-484f-8979-7b59035f0946"),
                            DDD = 41,
                            Name = "41 - Curitiba"
                        },
                        new
                        {
                            Id = new Guid("a97521e0-69ed-4471-b55a-7605235488db"),
                            DDD = 48,
                            Name = "48 - Florianópolis"
                        },
                        new
                        {
                            Id = new Guid("a3b9a17f-0900-4796-9122-2c6722845a6a"),
                            DDD = 51,
                            Name = "51 - Porto Alegre"
                        },
                        new
                        {
                            Id = new Guid("7de5130e-1112-467d-a010-f9a9b04ba8ab"),
                            DDD = 61,
                            Name = "61 - Brasília"
                        },
                        new
                        {
                            Id = new Guid("ffe7cddc-b27f-4908-87cd-4ff6ec0bfc10"),
                            DDD = 62,
                            Name = "62 - Goiânia"
                        },
                        new
                        {
                            Id = new Guid("3f900447-a62f-4698-be0a-283ea7571b4f"),
                            DDD = 63,
                            Name = "63 - Palmas"
                        },
                        new
                        {
                            Id = new Guid("602ef38a-3a3f-4765-8d01-42ac8a15f319"),
                            DDD = 65,
                            Name = "65 - Cuiabá"
                        },
                        new
                        {
                            Id = new Guid("1064a30a-4230-40d4-8e7e-b6552214fd4a"),
                            DDD = 67,
                            Name = "67 - Campo Grande"
                        },
                        new
                        {
                            Id = new Guid("c076a959-b0fc-488b-871c-e6d60964ad8d"),
                            DDD = 68,
                            Name = "68 - Rio Branco"
                        },
                        new
                        {
                            Id = new Guid("da824844-3651-4a4f-976b-d568e534783e"),
                            DDD = 69,
                            Name = "69 - Porto Velho"
                        },
                        new
                        {
                            Id = new Guid("9976f5a2-8d88-4b2e-b7b0-ae6a531e35a4"),
                            DDD = 71,
                            Name = "71 - Salvador"
                        },
                        new
                        {
                            Id = new Guid("46c18361-0a5b-45cf-ade7-c4d8611a0300"),
                            DDD = 79,
                            Name = "79 - Aracaju"
                        },
                        new
                        {
                            Id = new Guid("26b8789d-85f7-4fd8-ab8d-99a77f7dc2de"),
                            DDD = 81,
                            Name = "81 - Recife"
                        },
                        new
                        {
                            Id = new Guid("499d33d6-aae4-42ca-b876-c5fdaa52aa28"),
                            DDD = 82,
                            Name = "82 - Maceió"
                        },
                        new
                        {
                            Id = new Guid("d5541227-d002-47a1-81f4-2577ba036c56"),
                            DDD = 83,
                            Name = "83 - João Pessoa"
                        },
                        new
                        {
                            Id = new Guid("37ecae54-d0ac-41b2-9c8a-219c3d10583a"),
                            DDD = 84,
                            Name = "84 - Natal"
                        },
                        new
                        {
                            Id = new Guid("543d43c4-315f-4117-a2b3-e202509e1c69"),
                            DDD = 85,
                            Name = "85 - Fortaleza"
                        },
                        new
                        {
                            Id = new Guid("a12e88a2-5d60-4646-9373-0eda16ade298"),
                            DDD = 86,
                            Name = "86 - Teresina"
                        },
                        new
                        {
                            Id = new Guid("16f8b52d-0858-4398-ba13-482191adc44e"),
                            DDD = 91,
                            Name = "91 - Belém"
                        },
                        new
                        {
                            Id = new Guid("9350fcf1-8d37-4af8-a1bb-34b2482059c4"),
                            DDD = 92,
                            Name = "92 - Manaus"
                        },
                        new
                        {
                            Id = new Guid("453ce548-b73e-48a2-9413-8d0df2bec509"),
                            DDD = 95,
                            Name = "95 - Boa Vista"
                        },
                        new
                        {
                            Id = new Guid("5c12ed7f-2eae-45cc-9111-5a4d246a0a39"),
                            DDD = 96,
                            Name = "96 - Macapá"
                        },
                        new
                        {
                            Id = new Guid("623ab703-b5f1-4208-a4aa-82de97eb696b"),
                            DDD = 98,
                            Name = "98 - São Luís"
                        });
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.Contact", b =>
                {
                    b.HasOne("TechChallenge1.Domain.Models.State", "State")
                        .WithMany("Contacts")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("TechChallenge1.Domain.Models.State", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
