using TechChallenge1.Domain.Models;

namespace TechChallenge1.Data.Context;

public static class StateList
{
    public static IEnumerable<State> List { get; set; } = new List<State>
    {
        new() { DDD = 11, Name = "São Paulo" },
        new() { DDD = 12, Name = "São Paulo" },
        new() { DDD = 13, Name = "São Paulo" },
        new() { DDD = 14, Name = "São Paulo" },
        new() { DDD = 15, Name = "São Paulo" },
        new() { DDD = 16, Name = "São Paulo" },
        new() { DDD = 17, Name = "São Paulo" },
        new() { DDD = 18, Name = "São Paulo" },
        new() { DDD = 19, Name = "São Paulo" },
        new() { DDD = 21, Name = "Rio de Janeiro" },
        new() { DDD = 22, Name = "Rio de Janeiro" },
        new() { DDD = 24, Name = "Rio de Janeiro" },
        new() { DDD = 27, Name = "Espírito Santo" },
        new() { DDD = 28, Name = "Espírito Santo" },
        new() { DDD = 31, Name = "Minas Gerais" },
        new() { DDD = 32, Name = "Minas Gerais" },
        new() { DDD = 33, Name = "Minas Gerais" },
        new() { DDD = 34, Name = "Minas Gerais" },
        new() { DDD = 35, Name = "Minas Gerais" },
        new() { DDD = 37, Name = "Minas Gerais" },
        new() { DDD = 38, Name = "Minas Gerais" },
        new() { DDD = 41, Name = "Paraná" },
        new() { DDD = 42, Name = "Paraná" },
        new() { DDD = 43, Name = "Paraná" },
        new() { DDD = 44, Name = "Paraná" },
        new() { DDD = 45, Name = "Paraná" },
        new() { DDD = 46, Name = "Paraná" },
        new() { DDD = 47, Name = "Santa Catarina" },
        new() { DDD = 48, Name = "Santa Catarina" },
        new() { DDD = 49, Name = "Santa Catarina" },
        new() { DDD = 51, Name = "Rio Grande do Sul" },
        new() { DDD = 53, Name = "Rio Grande do Sul" },
        new() { DDD = 54, Name = "Rio Grande do Sul" },
        new() { DDD = 55, Name = "Rio Grande do Sul" },
        new() { DDD = 61, Name = "Distrito Federal" },
        new() { DDD = 62, Name = "Goiás" },
        new() { DDD = 64, Name = "Goiás" },
        new() { DDD = 63, Name = "Tocantins" },
        new() { DDD = 65, Name = "Mato Grosso" },
        new() { DDD = 66, Name = "Mato Grosso" },
        new() { DDD = 67, Name = "Mato Grosso do Sul" },
        new() { DDD = 68, Name = "Acre" },
        new() { DDD = 69, Name = "Rondônia" },
        new() { DDD = 71, Name = "Bahia" },
        new() { DDD = 73, Name = "Bahia" },
        new() { DDD = 74, Name = "Bahia" },
        new() { DDD = 75, Name = "Bahia" },
        new() { DDD = 77, Name = "Bahia" },
        new() { DDD = 79, Name = "Sergipe" },
        new() { DDD = 81, Name = "Pernambuco" },
        new() { DDD = 87, Name = "Pernambuco" },
        new() { DDD = 86, Name = "Piauí" },
        new() { DDD = 89, Name = "Piauí" },
        new() { DDD = 82, Name = "Alagoas" },
        new() { DDD = 83, Name = "Paraíba" },
        new() { DDD = 84, Name = "Rio Grande do Norte" },
        new() { DDD = 85, Name = "Ceará" },
        new() { DDD = 88, Name = "Ceará" },
        new() { DDD = 96, Name = "Amapá" },
        new() { DDD = 92, Name = "Amazonas" },
        new() { DDD = 97, Name = "Amazonas" },
        new() { DDD = 91, Name = "Pará" },
        new() { DDD = 93, Name = "Pará" },
        new() { DDD = 94, Name = "Pará" },
        new() { DDD = 95, Name = "Roraima" },
        new() { DDD = 98, Name = "Maranhão" },
        new() { DDD = 99, Name = "Maranhão" }
    };
}
